---
Backend: Rally222
PredefinedBackendHeaders:
  Rally:
    Content-Type:
      overwrite: true
      value: quick.store.contentType
    userId:
      overwrite: true
      value: quick.store.userId
    intUnit:
      overwrite: false
      value: quick.store.intUnit
    corrr:
      overwrite: false
      value: quick.store.corrr
    tenant:
      overwrite: false
      value: quick.store.tenant
DomainModuleList:
Header:
  Content-Type:
    overwrite: true
    value: test1
  userId:
    overwrite: false
    value: test2
  corrr:
    overwrite: false
    value: test3
HeaderExceptionList:
  login: "/services/authorization/api/authentication/authenticate"
regionalDefinition:
- region: tr
  FormattingDefinition:
    groupSeparator:
      overwrite: true
      value: "."
    radixPoint:
      overwrite: true
      value: ","
    digits:
      overwrite: false
      value: 2
    enforceDigitsOnBlur:
      overwrite: true
      value: true
    longDateFormat: 
      overwrite: true
      value: "DD-MM-YYYY HH-MM"
    longTimeFormat: 
      overwrite: true
      value: "HH-MM-SS"
    shortTimeFormat: 
      overwrite: true
      value: "HH-MM"
    moneyFormat: 
      overwrite: true
      value: "en-US"
    serviceDateFormat:
      overwrite: true
      value: 'YYYY-MM-DDTHH:mm:ss.SSS[Z]'
    displayDateFormat:
      overwrite: true
      value: 'dd/MM/yyyy'
- region: en
  FormattingDefinition:
    groupSeparator:
      overwrite: true
      value: "."
    radixPoint:
      overwrite: true
      value: ","
    digits:
      overwrite: false
      value: 3
    enforceDigitsOnBlur:
      overwrite: true
      value: true
    longDateFormat: 
      overwrite: true
      value: "DD-MM-YYYY HH-MM"
    longTimeFormat: 
      overwrite: true
      value: "HH-MM-SS"
    shortTimeFormat: 
      overwrite: true
      value: "HH-MM"
    moneyFormat: 
      overwrite: true
      value: "en-US"
    serviceDateFormat:
      overwrite: true
      value: 'YYYY-MM-DDTHH:mm:ss.SSS[Z]'
    displayDateFormat:
      overwrite: true
      value: 'dd/MM/yyyy'
csspath: 
- /settings/css/asd.css

pipelineqjson: /settings/qjson/myPipe.qjson
rootqjson: /static/test.qjson
fileMap: 
- id: h09wa83s-bnei-a66v-zoi5-emf0mj21p3r7
  path: /static
  name: /testt.qjson
  version: Mon Dec 15 2025 19:15:19 GMT+0300 (GMT+03:00)
- id: vuo0vkav-4ytx-mpt4-6mtc-wdp0mj7aivdj
  path: /static
  name: /frame1.qjson
  version: Mon Dec 15 2025 19:06:51 GMT+0300 (GMT+03:00)
- id: 4ejv51an-y04g-isbp-mlkw-35v0mj7cg73p
  path: /static
  name: /frame2.qjson
  version: Mon Dec 15 2025 19:05:21 GMT+0300 (GMT+03:00)
- id: xbcucm6w-idjk-t0cx-s8mu-4ff0mdq3erdk
  path: /static
  name: /App Settings.appSettings
  version: Mon Dec 15 2025 02:42:43 GMT+0300 (GMT+03:00)
- id: w2yxkjta-ro26-62li-k8gh-xfm0mdswtp8j
  path: /static
  name: /test.qjson
  version: Mon Dec 15 2025 19:20:11 GMT+0300 (GMT+03:00)
- id: 5zzae613-vl3z-jvdp-8vo7-5n10mfxd9k8f
  path: /settings/css
  name: /asd.css
  version: Mon Dec 15 2025 02:42:44 GMT+0300 (GMT+03:00)
- id: oq15k3yr-2llw-4vqd-ae74-2sx0mj6d9ihx
  path: /static
  name: /blankPage.qjson
  version: Mon Dec 15 2025 19:06:40 GMT+0300 (GMT+03:00)
- id: mdcxy6pc-fha6-na3n-no84-0hc0mj6dbrzj
  path: /static
  name: /Home1.qjson
  version: Mon Dec 15 2025 19:18:25 GMT+0300 (GMT+03:00)
- id: ytfu45vo-h42q-vrsb-020l-1zv0mj7cncsz
  path: /static
  name: /blankkk.qjson
  version: Mon Dec 15 2025 19:09:42 GMT+0300 (GMT+03:00)
- id: af4q1w4c-rfvs-d9ba-iv7y-5io0mj7czvma
  path: /static
  name: /onboard.qjson
  version: undefined

settings: <<settings:my4gu86w-avc6-no17-rnjl-mp80mdx0soq2>>
siteTitle: qwew
useShadowDOM: false
pipeline: <<pipeline:lmntyso9-g0q9-s88h-w5mu-oax0mihcao2y>>

appSettings:
  general:
    settings: <<settings:my4gu86w-avc6-no17-rnjl-mp80mdx0soq2>>
    siteTitle: qwew
    useShadowDOM: false
    pipeline: <<pipeline:lmntyso9-g0q9-s88h-w5mu-oax0mihcao2y>>
  themeSettings:
    defaultTheme: Theme1
    themes:
      - name: Theme1
        lightTheme:
          colors:
            - name: Background
              allowGradient: true
              color: '#1e4aa2'
            - name: Text
              allowGradient: false
              color: '#212121'
            - name: Primary
              allowGradient: false
              color: '#151233'
            - name: Secondary
              allowGradient: false
              color: '#FD454C'
            - name: Tertiary
              allowGradient: false
              color: '#007C77'
            - name: Passive
              allowGradient: false
              color: '#7A95B0'
            - name: Info
              allowGradient: false
              color: '#03A9F4'
            - name: Success
              allowGradient: false
              color: '#00BB41'
            - name: Warning
              allowGradient: false
              color: '#F3CA40'
            - name: Error
              allowGradient: false
              color: '#F44336'
          fonts:
            - fontClassName: Default
              configs:
                fontFamily: Nunito
                fontColor: '#000000'
                fontSize: 16px
                displayWeight: Weight - 1000
                fontWeight: '1000'
                combinedFont: Nunito-Weight
                fontStyle: normal
                fontOptions: []
            - fontClassName: Heading 1
              configs:
                fontFamily: Source Sans Pro Italic
                fontColor: '#000000'
                fontSize: 24px
                displayWeight: Black - 900
                fontWeight: '900'
                combinedFont: SourceSansPro-BlackItalic
                fontStyle: italic
                fontOptions: []
            - fontClassName: Heading 2
              configs:
                fontFamily: Montserrat Italic
                fontColor: '#000000'
                fontSize: 16px
                displayWeight: Extra Light - 200
                fontWeight: '200'
                combinedFont: Montserrat-ExtraLightItalic
                fontStyle: italic
                fontOptions: []
            - fontClassName: Heading 3
              configs:
                fontFamily: Lato Italic
                fontColor: '#000000'
                fontSize: 12px
                displayWeight: Black - 900
                fontWeight: '900'
                combinedFont: Lato-BlackItalic
                fontStyle: italic
                fontOptions: []
            - fontClassName: Paragraph
              configs:
                fontFamily: Roboto
                fontColor: '#000000'
                fontSize: 12px
                displayWeight: Regular - 400
                fontWeight: '400'
                combinedFont: Roboto-Regular
                fontStyle: normal
                fontOptions: []
            - fontClassName: Info
              configs:
                fontFamily: Roboto
                fontColor: '#000000'
                fontSize: 12px
                displayWeight: Regular - 400
                fontWeight: '400'
                combinedFont: Roboto-Regular
                fontStyle: normal
                fontOptions: []
    themeModelId: p9idilmq-um2y-90a7-7lf0-1ph0mdq3febr
